DROP TABLE IF EXISTS QUOTES;

CREATE TABLE QUOTES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  isin VARCHAR(12) DEFAULT NULL,
  bid NUMERIC DEFAULT NULL,
  ask NUMERIC DEFAULT NULL,
  elvl NUMERIC DEFAULT NULL
);